define({
  "name": "YACUNA API",
  "version": "1.0.0",
  "description": "Trading API Description",
  "apidoc": "<h2 id=\"authentication\">Authentication</h2>\n<p>To be able to use the Yacuna Trading API you need a valid Yacuna account.<br>\nIn your settings area you should get &quot;API Token Id&quot; and &quot;API Token Secret&quot;.<br>\nUsing those data you can generate the &quot;Api-Token&quot; to be passed with each API call within HTTP headers.<br>\nAs additional security one time password can be added.</p>\n<p>Example of HTTP header data needed for the call authentication:</p>\n<pre><code>{\n&quot;Api-Token-Id&quot;: &quot;AAEAAAgfi0NjCp9rrgTVM2-BBrP6AgkykwBEwFj74fcHFkNpmcsgjLph&quot;,\n&quot;Api-Token&quot;: &quot;1401710118967Tcdbbf266b260a494ed99d0037de0c5c8353934335bd9656c8c4d1b449602f6c62231446b727f3a1e9918919af6bfdba574f5e245fe132e1fff04b4c111b72823&quot;,\n&quot;Api-Token-OTP&quot;: &quot;&quot;\n}\n</code></pre><p><strong>Example code in JavaScript how to calculate Api-token</strong></p>\n<pre class=\"prettyprint language-javascript prettyprinted\" data-type=\"json\" style=\"\">\n<code>\nfunction createTokenHeaders(requestMethod, requestUrl, requestQueryString, requestBody) {\n    if (isEmpty(tokenId)) {\n        return {};\n    }\n    var tokenSalt = '' + new Date().getTime();\n    var hashInput = tokenSalt + '@' + tokenSecret + '@' + requestMethod + '@' + requestUrl;\n    if (!isEmpty(requestQueryString)) {\n        hashInput = hashInput + '?' + requestQueryString;\n    }\n    if (!isEmpty(requestBody)) {\n        hashInput = hashInput + '@' + createRequestBodyForSignature(requestBody);\n    }\n    var hasher = new jsSHA(hashInput, 'TEXT');\n    return {\n        'Api-Token-Id': tokenId,\n        'Api-Token': tokenSalt + 'T' + hasher.getHash(\"SHA-512\", \"HEX\"),\n        'Api-Token-OTP': tokenOTP\n    };\n}\n</code>\n</pre>\n\n",
  "generator": {
    "version": "0.4.3",
    "time": "2014-06-02T12:13:42.349Z"
  }
});